# ********RoostGPT********

# Test generated by RoostGPT for test api-fulfilment using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=99e96e3191
# 
# 

# ********RoostGPT********
Feature: Product Order Information Required Event

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def auth_token = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(auth_token)' }
    * path '/listener/productOrderInformationRequiredEvent'

  Scenario Outline: Verify the endpoint for Product Order Information Required Event
    Given request <requestBody>
    When method post
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('listener_productOrderInformationRequiredEvent_post.csv') |
