# ********RoostGPT********

# Test generated by RoostGPT for test api-fulfilment using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=10f12a7f6a
# 
# 

# ********RoostGPT********
Feature: Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def requestBody = { "notification": { "date": "2021-06-05T20:23:29-03:00", "order": { "id": "20230315000001", "associatedDocument": "VTT001", "correlationOrder": "10" } } }

  Scenario Outline: Validate Product Order Create Event API
    Given path '/listener/productOrderCreateEvent'
    And request requestBody
    When method post
    Then status <status>
    And match response == <response>

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |
