# ********RoostGPT********

# Test generated by RoostGPT for test api-fulfilment using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /productOrder_post for http method type POST 
# RoostTestHash=d2b09bfc44
# 
# 

# ********RoostGPT********
Feature: Product Order API feature

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test Product Order API endpoint with different response codes
    Given path '/productOrder'
    And def authHeader = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }
    And header authHeader
    And request {}
    When method post
    Then status <status_code>
    And match response contains { type:'#string', message:'#string', code:'#string' }

    Examples:
      | read('productOrder_post.csv') |

  Scenario: Test Product Order API endpoint with 201 response code
    Given path '/productOrder'
    And def authHeader = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }
    And header authHeader
    And request {}
    When method post
    Then status 201
    And match response contains { control: '#object', order:'#object'}
    And match response.control == { type:'#string', message:'#string', code:'#string' }
    And match response.order == { id:'#string' }
